swagger: "2.0"
info:
  version: "1.0.0"
  title: "My API"
paths:
  /path:
    post:
      summary: "Create a new pet"
      operationId: "createPet"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Pet object that needs to be added to the store"
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        200:
          description: "Pet created successfully"
          schema:
            $ref: "#/definitions/Pet"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
definitions:
  Pet:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      photoUrls:
        type: "array"
        items:
          type: "string"
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "pet status in the store"
    required:
      - "name"
      - "photoUrls"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    required:
      - "name"
